USER_ESG_AWARENESS_RATE = "USER_ESG_AWARENESS_RATE"
USER_IMPACT_INVESTMENT_RATE = "USER_IMPACT_INVESTMENT_RATE"
USER_GREEN_INDUSTRY_THRESHOLD = "USER_GREEN_INDUSTRY_THRESHOLD"
USER_RISK_TOLERANCE = "USER_RISK_TOLERANCE"

# user preference
USER_E_WEIGHT = "USER_E_WEIGHT"
USER_S_WEIGHT = "USER_S_WEIGHT"
USER_G_WEIGHT = "USER_G_WEIGHT"

# Used to filter investment universe
USER_CONTROVERSY_THRESHOLD = "USER_CONTROVERSY_THRESHOLD"
USER_ESG_SCORE_THRESHOLD = "USER_ESG_SCORE_THRESHOLD"
USER_SECTORS = "USER_SECTORS"
